services:

  # Backend
  chatbot-back:
    build:
      context: ../
      dockerfile: Dockerfile
    image: back-chatbot-image
    ports:
      - "3004:3000"
    environment:
      DB_PASSWORD: pohapp2024
      DB_HOST: db-pohapp
      DB_USER: root
      DB_PORT: 3306
      DB_DATABASE: chatbot-host
    container_name: back-chatbot-container